language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: VDi9Mpy6kc2h4cLU13cEg+qxCE3IjpMX9em0hgHHSPxowdrKU7bPcWoJTBGToMt/6VfNMAbLyqsAkMyBAs79Y3XtX5Z0fmMkbjDgSRuTrybg+B6QQmE7VHJbcG4mn0Bw32DtgUlspmeAKEnHpe6d3fbIi5evgs4tbof7YnCZYg8=
  - secure: jEdjbh0+G8u8WEhG6MZWpQqQgAzacHMfcRK3K8JxnS14zKRNclk41bbR2lD7p4AOoo6VzZzOV46I7ecYmv0YkC44Pk7VbYEEhgF84VI/9MEg/gInFz9Jo6RGtKwgdFTx68WXiaDUrERptaQMw9ySdsV1o0We/57oXwHIyzmqE2g=
