language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: PS/2RyaQmEtWHmpxIXh4yjIXI5sir7VcT6k4G3/omalU14Z17+q01rWBnml6P/0BTJjZBnONqqQKTDmDf1MZnY2GK2Tq6KcsS0Q4C+64M8ky3X8RlUYC9mdIkM8GO0eozOOtNeWQlVw2vTBbA6KGPfQHyxR+ZvTCMX7+tPU7HCo=
  - secure: SBgLRmoxo530svQidWunCK8az3UuBV8Y9CCogttjd4e/XLfTwJHHMM/P/AZKYsvMlHm5jj3T04dqu3h8kV2YojALcZf/4SOV++pWZEFD3DzwklzkHFVKgFbm/xEPkcpzc37vvaM6wjRvDQ3QtQpq0Ncx9GOQoWqoggJ/DP1N/DM=
